version: '3.9'
services:
  api:
    image: node:16.11.0-alpine3.14
    container_name: learn-nest-cqrs-api
    ports:
      - 13333:3333
    environment:
      - LANG=C.UTF-8
    volumes:
      - .:/app:cached
      - type: volume
        source: node-modules
        target: /app/node_modules
    working_dir: /app
    restart: always
    tty: true
    command:
      - ash
      - -c
      - |
        npm ci
        npm run build
        npm run start:debug
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:13.4-alpine3.14
    container_name: learn-nest-cqrs-database
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C.UTF-8'
      LANG: C.UTF-8
    restart: always
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./db/init
        target: /docker-entrypoint-initdb.d
    healthcheck:
      test: pg_isready
      interval: 3s
      timeout: 5s
      retries: 5
volumes:
  db-data:
  node-modules:
